myDf<-read.csv("C:/Users/Younes/Desktop/TP_FDDTA/TP1/2008.csv") 
head(myDf)
head(myDf$Origin) 
tail(myDf$Origin)
head(myDf$Origin=="IND") 
sum(myDf$Origin=="IND") 
sum(myDf$Dest=="IND") 
sum(myDf$Origin=="ORD") 
sum(myDf$Dest=="ORD") 
??AND
sum(myDf$Origin=="IND" & myDf$Dest=="ORD") 
myIndyOrigins<-subset(myDf,myDf$Origin=="IND") 
myIndyDest<-subset(myDf,myDf$Dest=="IND") 
head(myIndyDest) 
table(myIndyOrigins$Month)
plot(table(myIndyOrigins$Month)) 
sum(myDf$Origin=="TUP") 
mean(myDf$Origin=="TUP") 
myTUPOrigins<-subset(myDf, myDf$Origin=="TUP") 
mean(myTUPOrigins$DepDelay) 
sum(myIndyOrigins$DepTime<600, na.rm=TRUE) 
sum(myIndyOrigins$DepTime<1200, na.rm=TRUE) 
sum(myIndyOrigins$DepTime<1800, na.rm=TRUE)
sum(myIndyOrigins$DepTime<2400, na.rm=TRUE) 
sum(is.na(myIndyOrigins$DepTime))
sum(myDf$Dest=="LAX")
sum(myDf$Origin=="ATL" & myDf$Dest=="LAX")
myATLandLAX<-subset(myDf, myDf$Origin=="ATL" & myDf$Dest=="LAX")
sum(myATLandLAX$DepTime<1200, na.rm=TRUE) 
table(myATLandLAX$DepTime) 
plot(table(myATLandLAX$DepTime)) 
plot(table(myIndyOrigins$Month))
plot(table(myATLandLAX$DepTime)) 
