rm(list=ls())
setwd("C:/Users/Younes/Desktop/TP_FDDTA/TP2.2") 
fromage <- read.table(file="fromage.txt",header=T,row.names=1,sep="\t",dec=".") 
print(head(fromage)) 
print(summary(fromage)) 
pairs(fromage) 
groupes.kmeans <- kmeans(fromage,centers=4,nstart=5) 
print(groupes.kmeans) 
d.fromage <- dist(fromage) 
cah_clink <- hclust(d.fromage,method="complete") 
plot(cah_clink) 
rect.hclust(cah_clink,k=4) 
groupes.cah <- cutree(cah_clink,k=4) 
print(sort(groupes.cah)) 
